# Generated by Django 4.0.3 on 2022-04-13 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 4, 13, 18, 37, 29, 532491))),
                ('image', models.TextField(blank=True, db_column='image64')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
    ]
