# Generated by Django 4.0.3 on 2022-04-05 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lobby',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Lobbies'},
        ),
        migrations.AlterField(
            model_name='lobby',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 21, 2, 39, 4927)),
        ),
    ]
