# Generated by Django 4.0.3 on 2022-04-05 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lobby_options_alter_lobby_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game',
            new_name='lobby',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 22, 18, 19, 424974)),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together={('lobby',)},
        ),
    ]
