# Generated by Django 4.0.3 on 2022-04-06 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_game_player_lobby_alter_lobby_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 15, 43, 34, 929097)),
        ),
    ]
