# Generated by Django 4.0.3 on 2022-04-06 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lobby_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 21, 16, 7, 12573)),
        ),
    ]
