# Generated by Django 4.0.3 on 2022-04-13 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_lobby_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 18, 37, 29, 525487)),
        ),
    ]
