# Generated by Django 4.0.3 on 2022-04-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together={('card_id',)},
        ),
    ]
