# Generated by Django 4.0.3 on 2022-04-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lobby_date'),
        ('loto', '0002_card_card_id_alter_card_index_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='lobby',
            new_name='player',
        ),
        migrations.AlterIndexTogether(
            name='winner',
            index_together={('player',)},
        ),
    ]
