# Generated by Django 4.0.3 on 2022-04-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_lobby_date'),
        ('loto', '0004_alter_card_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lobby'),
        ),
    ]
